Task 6
DKARAGODIN/formal-lang-course pull request #6
Opened 2023-03-31 17:04 UTC by DKARAGODIN

2023-04-01 11:09 UTC, rustam-azimov requested changes

2023-04-01 11:09 UTC, rustam-azimov commented on project/context_free_grammar_util.py
> +    cleared_cfg = (cfg.remove_useless_symbols().eliminate_unit_productions().remove_useless_symbols())
здесь можно убрать первое удаление бесполезных правил

2023-04-01 12:16 UTC, DKARAGODIN commented on project/context_free_grammar_util.py
> +    cleared_cfg = (cfg.remove_useless_symbols().eliminate_unit_productions().remove_useless_symbols())
Убрал.
Тесты проходят

2023-04-02 08:51 UTC, rustam-azimov approved these changes

2023-04-02 08:52 UTC, merged