Task 7
DKARAGODIN/formal-lang-course pull request #7
Opened 2023-04-07 13:06 UTC by DKARAGODIN

2023-04-07 14:08 UTC, rustam-azimov requested changes

2023-04-07 14:08 UTC, rustam-azimov commented on project/ecfg_util.py
> +def get_ecfg_from_string(text: str, start_symbol: Variable = Variable("S")) -> ECFG:
Лучше как методы классов сделать

2023-04-07 14:08 UTC, rustam-azimov commented on project/ecfg_util.py
> +    dfa: DeterministicFiniteAutomaton
Предусмотрите также в РКА получать матрицы смежности конечных автоматов.

2023-04-08 11:06 UTC, DKARAGODIN commented on project/ecfg_util.py
> +def get_ecfg_from_string(text: str, start_symbol: Variable = Variable("S")) -> ECFG:
Сдалал соответствующие статические методы

2023-04-08 11:07 UTC, DKARAGODIN commented on project/ecfg_util.py
> +    dfa: DeterministicFiniteAutomaton
Добавил.
Воспользовался уже ранее созданным классом.
Тесты добавил.

2023-04-09 09:34 UTC, rustam-azimov approved these changes

2023-04-09 21:58 UTC, merged