Task 8 Hellings
DKARAGODIN/formal-lang-course pull request #8
Opened 2023-04-15 13:48 UTC by DKARAGODIN

2023-04-18 09:12 UTC, rustam-azimov requested changes

2023-04-18 09:12 UTC, rustam-azimov commented on project/rpq.py
> +def hellings(cfg: CFG, graph: nx.MultiDiGraph) -> Set[Tuple]:
нужно предусмотреть возможность получать грамматику и граф в разных форматах, например из файла.

2023-04-19 08:41 UTC, DKARAGODIN commented on project/rpq.py
> +def hellings(cfg: CFG, graph: nx.MultiDiGraph) -> Set[Tuple]:
У нас же уже есть функции которые это делают. Подумал что пользователь сам должен отвечать за то чтобы предоставить данные с правильным типом.
Добавил одну прокси функцию для удобства.

2023-04-24 10:54 UTC, rustam-azimov commented on project/rpq.py
> +def hellings(cfg: CFG, graph: nx.MultiDiGraph) -> Set[Tuple]:
Да, понимаю, но задание так сформулировано. И можно снять некоторую ответственность с пользователя.

2023-04-24 10:55 UTC, rustam-azimov approved these changes

2023-05-06 06:58 UTC, merged